# Generated by Django 4.0.5 on 2022-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_name', models.CharField(max_length=100)),
                ('tgt_col', models.CharField(max_length=100)),
                ('variables', models.CharField(max_length=500)),
                ('var_types', models.CharField(max_length=200)),
                ('imp_method', models.CharField(max_length=100)),
                ('sampling_method', models.CharField(max_length=100)),
                ('sele_method', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=300)),
            ],
        ),
    ]
